default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: disney-api_development

test:
  <<: *default
  database: disney-api_test

production:
  <<: *default
  database: twitter-clone_production